### PR TITLE
Freerouting daemon & progress update

### PR DESCRIPTION
**Pull request by L1uTongweiNewAccount**
This PR will upload a folder named `scripts` to save all scripts.

Updated:

- Bash Script `freeroutingd` (Freerouting Daemon) to automatically make a fake X11 desktop to run headless freerouting.
- C++ program `freeroutingp` (Freerouting Progress) translate the log of freerouting to `stderr` stream by pipe.
- A fast test dsn file as `tests/FastTest.dsn`

Set environment variable `JAVA`, you can set the jre what freerouting uses.

Set environment variable `ARG_GUI` can enable GUI (for OS like Windows)

Now we only can write `{"status": "startRoute"}`, `{"status": "routeProgress"}`, `{"status": "routeResult"}`, `{"status": "startOptimize"}` and `{"status": "optimizeResult"}`.

Bugs:

- `{"status": "routeProgress"}` doesn't work in my computer. Because no message `Saving xxx...` sent. Please update log system to output real information in routing, like pass number, etc.
- Sometimes the freerouting will push a dialog like "There is a snapshot. Would you like use this snapshot?". Headless cannot cancel this dialog.
- Sometimes there will be a net exception. But no effect for auto-routing.

like:

```
java.util.concurrent.CompletionException: java.net.ConnectException
        at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
        at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.net.ConnectException
        at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1028)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:227)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:280)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$2(PlainHttpConnection.java:238)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        ... 5 more
Caused by: java.nio.channels.ClosedChannelException
        at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:202)
        at java.base/sun.nio.ch.SocketChannelImpl.beginConnect(SocketChannelImpl.java:786)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:874)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:210)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:212)
        ... 9 more
```

### CODE REVIEW

**Comment by L1uTongweiNewAccount** [comment]
For now, `freeroutingp` is just for test. 

We must update the log system to provide more information, and `freeroutingp` will be more useful.

If we can convert .ses to EasyEDA's API format, we can compatible with it. (See #311)

(For now, I can't, but maybe I can develop a electron plugin for EasyEDA, and it also can make the same effect)

And thanks for @leoheck to provide this idea in #241.

@andrasfuchs

**Comment by andrasfuchs** [comment]
This is great work, thank you @L1uTongweiNewAccount!

Could you include some batch nstructions how to compile the .cpp file? I can see the Makefile, but what tools I need to install for it to work?

It would be great if I could build and test it locally.

**Comment by L1uTongweiNewAccount** [comment]
> 这是伟大的工作，谢谢！
> 
> 你能包括一些批处理指令如何编译.cpp文件吗？我可以看到 Makefile，但我需要安装哪些工具才能正常工作？
> 
> 如果我能在本地构建和测试它，那就太好了。

Just `make`. 

You may need `g++` and bash, only these.

**Comment by andrasfuchs** [comment]
@L1uTongweiNewAccount 

I could make the C++ compilation work on Ubuntu 👍 

Added a README to make it easier for others to use these scripts.

Regarding the bugs:
- The logs can be made more verbose by [changing the log4j log level to TRACE or ALL](https://logging.apache.org/log4j/2.x/manual/customloglevels.html)
- The dialog should disappear in the 2.0 version, because snapshots will be disabled by default (you can check [the SNAPSHOT version](https://github.com/freerouting/freerouting/releases/tag/SNAPSHOT) until we don't have a new release)

**Comment by andrasfuchs** [comment]
I added the '-ll' command line argument for the ability to change the file log level.

**Comment by L1uTongweiNewAccount** [comment]
@andrasfuchs I am very sorry about I did not say clearly that how to use it.

I will write a better README and optimize the new freeroutingp with new log level (I will force it in freeroutingd)

Now freeroutingd just a launcher.

**Comment by L1uTongweiNewAccount** [comment]
@andrasfuchs Anyway, It's not enough good for this PR. I will improve it quickly,

**Comment by andrasfuchs** [comment]
Great, and no worries, take your time. 
You can always create a new PR with your improvements.

Thank you again for your contribution!

**Comment by L1uTongweiNewAccount** [comment]
@andrasfuchs I built the latest version and use the command line `-ll DEBUG` or `-ll 7` 

But no change shown.

If there is ever no DEBUG message? Or this is a bug?

If you can, please provide useable pre-build version for me.

**Comment by andrasfuchs** [comment]
You must use the snapshot version from here: https://github.com/freerouting/freerouting/releases/tag/SNAPSHOT

**Comment by andrasfuchs** [comment]
I run the following and got debug messages as well:
```
java -jar freerouting-SNAPSHOT-20240627_092100.jar -ll ALL
```

**Comment by andrasfuchs** [comment]
There might be an issue with the `changeFileLogLevel` method in some cases where the `LoggerContext` is not an instance of `org.apache.logging.log4j.core.LoggerContext`. So if you still don't get the debug messages, that might be the reason, and I need to spend more time on it later.

**Comment by L1uTongweiNewAccount** [comment]
@andrasfuchs The latest news is I found there is a bug that:

I can found debug message in logs/ folder

I cannout found debug message in stderr/stdout

**Comment by L1uTongweiNewAccount** [comment]
@andrasfuchs Maybe I can take over the connection between freerouting and log file.

But the easier method is fix the bug and we can get them in stdout

**Comment by L1uTongweiNewAccount** [comment]
Anyway, I am seeing the log file and believe I am seeing stdout.

You may add a option to disable the file log out.

**Comment by L1uTongweiNewAccount** [comment]
And there is also a problem: 

You may output progress in INFO information.

I cannot infer any progress in DEBUG information.

e.g.

```
INFO Progress: Auto-routing xxx To-route: xxx Completed: xxx Failed: xxx ...
INFO Progress: Optimize xxx ...
```

(Mind `...` and space)

**Comment by L1uTongweiNewAccount** [comment]
All right, I will move this issue to a new issue.

**Pull request merged**
