### PR TITLE
optimization-pulltight45degree

### PR DESCRIPTION
**Pull request by Djzhan0207**
This is an optimization for pulltight-45degree algorithm.
It can improve the performance when the PCB is very dense and the mode is under 45 °.

### CODE REVIEW

**Comment by Djzhan0207** [comment]
Freerouting uses too much memory is mainly because its searching queue has too many elements。
The endless loop is because Simplex.java 's intersection function has a endless loop，it occurs when 
a rectangle trying to intersects with an irregular borderline shape.Improving this algorithm or when this situations happens，
stoping it and restarting router cound help。

**Comment by L1uTongweiNewAccount** [comment]
Thank you, now I will use your code to solve my routing.

**Comment by andrasfuchs** [comment]
@L1uTongweiNewAccount Did you have the chance to test this modification? Does it work as you expected?

**Review by andrasfuchs — COMMENTED** [review]
I see that you commented out a few lines. It would be preferable if you completely removed them. Could you do that before I accept this PR?

**Comment by andrasfuchs** [comment]
Interestingly when I run the router with this PR it gets stuck at pass 8:

image

I used the following parameters:
`-de .\tests\Issue297-myboard.dsn -do .\tests\Issue297-myboard.ses`

This PR is still an improvement in this case, because the original code is stuck at the first pass.

**Comment by Djzhan0207** [comment]
Stuck is mainly because the endless loop mentioned above. This PR is just a time saver for dense PCB. 
You can remove the code's comment.
I think 90 router with 45 pulltight could route more fast.

**Comment by andrasfuchs** [comment]
I couldn't do enough testing to justify the code removal, so I will close this PR for now.

I don't disagree that it solves some problem for some people, I just can't verify if it breaks something for others.

These kinds of modifications that impact the core algorithm would need rigorous testing, that I can't do at the moment without implementing automated testing with multiple inputs and their expected outputs.

Nonetheless that your for your work, I hope to test it again at a later time when we have proper testing in place.

**Pull request closed without merging**
