### PR TITLE
Add Traditional Chinese (Taiwan) translations

### PR DESCRIPTION
**Pull request by Oliver0804**
Add Traditional Chinese (Taiwan) translations

### CODE REVIEW

**Comment by andrasfuchs** [comment]
This is great stuff, thank you a lot @Oliver0804! 🥇 

Note to myself: add `zh_tw` to the supported languages in the `GlobalSettings.java` as well.

**Comment by Oliver0804** [comment]
> This is great stuff, thank you a lot @Oliver0804! 🥇
> 
> Note to myself: add `zh_tw` to the supported languages in the `GlobalSettings.java` as well.

Thank you for your assistance. If any adjustments are needed, I will make the necessary changes.

**Comment by Oliver0804** [comment]
@andrasfuchs 
I have already made some changes to GlobalSettings.java. Could you please check if they are correct?
截圖 2024-06-26 凌晨12 38 43

**Comment by andrasfuchs** [comment]
I made two small changes before the merge:
- I changed the order or language checks, because "zh" and "zh-TW" both start with "zh" so we need to check for "zh-TW" first
- I made the parameter checking case insensitive and it now accepts both "zh-TW" and "zh_TW" as valid values

Thanks @Oliver0804 again for your work! 👍

**Pull request merged**
