### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by maksz42**
In this PR I tried to bring the codebase a bit closer to modern Java, as it looks like a big part comes from before Java 5. I tried my best not to break anything. There are no changes to the router engine (at least not intended :upside_down_face:). As a side effect, there is ~10% performance improvement coming probably from more efficient array copying. I also fixed small GUI bugs.

### CODE REVIEW

**Comment by maksz42** [comment]
Ok, I've just realized it's quite big :joy::joy::joy:
I can split it if necessary

**Comment by andrasfuchs** [comment]
Outstanding, thank you very much @maksz42!

I'll get into it next week, and let you know how it goes!

**Review by andrasfuchs — APPROVED** [review]

**Comment by andrasfuchs** [comment]
According my first few tests everything looks good.

I just wanted to note that I noticed that you changed the location of the counter to the other button:
image
vs
image

It was strange at first to be honest, but the more I see it the more I like it.

I'll get back to you when I did a more complete test, hopefully I can merge this PR next week the latest.

**Comment by maksz42** [comment]
I think it's more natural that the timer counts down the default option, like "Starting in 10, 9, 8...".

**Comment by andrasfuchs** [comment]
I've just merged your PR, thanks again for your work @maksz42!

**Pull request merged**
