### PR TITLE
Chinese Translation Update By L1uTongwei

### PR DESCRIPTION
**Pull request by L1uTongweiNewAccount**
To be a Chinese developer, I often be awful with bad Chinese Translations.

So, I change some Chinese Translations with errors or strange expression in Chinese.

But I am just a high school student, so I cannot translate some unclearly English expression.

Examples:

with can be 带着, 用, 关于, 伴随, ... in Chinese.

Because of unclearly expression, so I use this to adapt the context.

with=with (English)

with=关于（with） (Chinese)

That's because Chinese developer usually can read simple English.

Anyway, I know there are many Chinese develops with EasyEDA here, and I wish our develop can be easier with my PR.

@Djzhan0207 can you help me to improve this translation?

### CODE REVIEW

**Comment by L1uTongweiNewAccount** [comment]
NOTE: DRC 错误 = 设计规则检查错误，if you think this is unclearly, please edit it.

**Comment by L1uTongweiNewAccount** [comment]
and there is a problem, fanout mode will be very usefil for SMD projects. But in most of conditions, no one can find this option out. I wish the UI can be more clearly than now. Thanks.

**Comment by andrasfuchs** [comment]
Thank you for your efforts, I know that our localization is far from perfect at the moment.

I already made a significant modification to the localization engine that we have, so from now on we could have whole sentences as templates localized. 

For example: 
```
message_specctra_ses_saved=Saving Specctra session {{filename}} was successful. -> {{filename}} is now replaced by the `filename` variable
title=Freerouting v{{version}} -> {{version}} is now replaced by the `version` variable
```

This change will eventually remove all the short translation strings like `vias`, `with` etc. and will result a much better translation for all languages.

**Comment by andrasfuchs** [comment]
@L1uTongweiNewAccount Ah, yes, and I agree, fanout should be in a better place somewhere on the UI. 👍

**Comment by L1uTongweiNewAccount** [comment]
@andrasfuchs Thank you. A whole sentence is really important for some languages, anyway, thanks!

**Comment by L1uTongweiNewAccount** [comment]
R-C

**Comment by L1uTongweiNewAccount** [comment]
Thank you very much for this!

I can't wait to see my translation in new release!

**Comment by andrasfuchs** [comment]
@L1uTongweiNewAccount 🥇 Thank you for your contribution!

**Pull request merged**
